# Generated by Django 6.0.6 on 2026-07-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='network',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction_hash',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='verified_on_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='minimum_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='network',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='symbol',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction_reference',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='wallet_address',
            field=models.TextField(),
        ),
    ]
