# Generated by Django 6.0.6 on 2026-07-07 13:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_paymentmethod_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='earned_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_roi_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='next_roi_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='total_payouts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='roi_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('maturity', 'At Maturity')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remaining_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
